In [4]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.5.1-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vis/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/vis/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
Using cached numpy-2.5.1-cp314-cp314-macosx_14_0_arm64.whl (5.3 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.1 pandas-3.0.5

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('students.csv')

In [6]:
type (df)

pandas.DataFrame

In [7]:
df

,student_id,name,age,gender,city,math_score,science_score,english_score,grade,fees_paid
0,1,Arun Kumar,21,Male,Chennai,88,76,90,A,True
1,2,Priya Nair,22,Female,Kochi,95,89,92,A+,True
2,3,Rahul Sharma,20,Male,Mumbai,72,65,80,B,False
3,4,Sneha Iyer,23,Female,Bangalore,60,55,70,C,True
4,5,Vikram Das,21,Male,Delhi,45,50,60,D,False
5,6,Meera Pillai,22,Female,Thiruvananthapuram,91,88,85,A,True
6,7,Arjun Menon,24,Male,Hyderabad,78,82,74,B+,True
7,8,Divya Reddy,,Female,Chennai,55,60,65,C+,False
8,9,Kiran Patel,23,Male,Ahmedabad,82,79,88,B+,True
9,10,Lakshmi Bai,21,Female,Kochi,98,95,97,A+,True
10,11,Suresh Kumar,22,Male,Mumbai,30,40,50,F,False
11,12,Ananya Rao,20,Female,Bangalore,85,80,78,A,True
12,13,Ravi Shankar,25,Male,Delhi,70,68,75,B,False
13,14,Pooja Menon,22,Female,Thiruvananthapuram,88,91,89,A,True
14,15,Ajith Thomas,21,Male,Kochi,62,58,72,C+,True

In [8]:
df.head()

,student_id,name,age,gender,city,math_score,science_score,english_score,grade,fees_paid
0,1,Arun Kumar,21,Male,Chennai,88,76,90,A,True
1,2,Priya Nair,22,Female,Kochi,95,89,92,A+,True
2,3,Rahul Sharma,20,Male,Mumbai,72,65,80,B,False
3,4,Sneha Iyer,23,Female,Bangalore,60,55,70,C,True
4,5,Vikram Das,21,Male,Delhi,45,50,60,D,False

In [9]:
df.tail()

,student_id,name,age,gender,city,math_score,science_score,english_score,grade,fees_paid
10,11,Suresh Kumar,22,Male,Mumbai,30,40,50,F,False
11,12,Ananya Rao,20,Female,Bangalore,85,80,78,A,True
12,13,Ravi Shankar,25,Male,Delhi,70,68,75,B,False
13,14,Pooja Menon,22,Female,Thiruvananthapuram,88,91,89,A,True
14,15,Ajith Thomas,21,Male,Kochi,62,58,72,C+,True

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     15 non-null     int64
 1   name           15 non-null     str
 2   age            15 non-null     str
 3   gender         15 non-null     str
 4   city           15 non-null     str
 5   math_score     15 non-null     int64
 6   science_score  15 non-null     int64
 7   english_score  15 non-null     int64
 8   grade          15 non-null     str
 9   fees_paid      15 non-null     bool
dtypes: bool(1), int64(4), str(5)
memory usage: 1.2 KB

In [11]:
df.describe()

       student_id  math_score  science_score  english_score
count   15.000000   15.000000      15.000000      15.000000
mean     8.000000   73.266667      71.733333      77.666667
std      4.472136   19.619475      16.615254      13.025616
min      1.000000   30.000000      40.000000      50.000000
25%      4.500000   61.000000      59.000000      71.000000
50%      8.000000   78.000000      76.000000      78.000000
75%     11.500000   88.000000      85.000000      88.500000
max     15.000000   98.000000      95.000000      97.000000

In [ ]:
df.shape #(rows,column)

(15, 10)

In [14]:
df.shape[0]

15

In [15]:
df.shape[1]

10

In [16]:
print(f'The dataframe has {df.shape[0]} rows')

The dataframe has 15 rows

In [17]:
df.columns

Index(['student_id', 'name', 'age', 'gender', 'city', 'math_score',
       'science_score', 'english_score', 'grade', 'fees_paid'],
      dtype='str')

In [ ]:
df.name #as series

0       Arun Kumar
1       Priya Nair
2     Rahul Sharma
3       Sneha Iyer
4       Vikram Das
5     Meera Pillai
6      Arjun Menon
7      Divya Reddy
8      Kiran Patel
9      Lakshmi Bai
10    Suresh Kumar
11      Ananya Rao
12    Ravi Shankar
13     Pooja Menon
14    Ajith Thomas
Name: name, dtype: str

In [19]:
df['name'] #as series

0       Arun Kumar
1       Priya Nair
2     Rahul Sharma
3       Sneha Iyer
4       Vikram Das
5     Meera Pillai
6      Arjun Menon
7      Divya Reddy
8      Kiran Patel
9      Lakshmi Bai
10    Suresh Kumar
11      Ananya Rao
12    Ravi Shankar
13     Pooja Menon
14    Ajith Thomas
Name: name, dtype: str

In [20]:
df[['name']] #as dataframe

            name
0     Arun Kumar
1     Priya Nair
2   Rahul Sharma
3     Sneha Iyer
4     Vikram Das
5   Meera Pillai
6    Arjun Menon
7    Divya Reddy
8    Kiran Patel
9    Lakshmi Bai
10  Suresh Kumar
11    Ananya Rao
12  Ravi Shankar
13   Pooja Menon
14  Ajith Thomas

In [ ]:
s = df['name'] #series
s.shape # only 1 dimension

(15,)

In [23]:
d = df[['name']] #dataframe
d.shape # 2 dimensions

(15, 1)

In [24]:
df.head()

,student_id,name,age,gender,city,math_score,science_score,english_score,grade,fees_paid
0,1,Arun Kumar,21,Male,Chennai,88,76,90,A,True
1,2,Priya Nair,22,Female,Kochi,95,89,92,A+,True
2,3,Rahul Sharma,20,Male,Mumbai,72,65,80,B,False
3,4,Sneha Iyer,23,Female,Bangalore,60,55,70,C,True
4,5,Vikram Das,21,Male,Delhi,45,50,60,D,False

In [25]:
df.columns

Index(['student_id', 'name', 'age', 'gender', 'city', 'math_score',
       'science_score', 'english_score', 'grade', 'fees_paid'],
      dtype='str')

In [27]:
subdf = df[['name', 'age', 'gender']]

In [28]:
subdf

            name age  gender
0     Arun Kumar  21    Male
1     Priya Nair  22  Female
2   Rahul Sharma  20    Male
3     Sneha Iyer  23  Female
4     Vikram Das  21    Male
5   Meera Pillai  22  Female
6    Arjun Menon  24    Male
7    Divya Reddy      Female
8    Kiran Patel  23    Male
9    Lakshmi Bai  21  Female
10  Suresh Kumar  22    Male
11    Ananya Rao  20  Female
12  Ravi Shankar  25    Male
13   Pooja Menon  22  Female
14  Ajith Thomas  21    Male

In [30]:
df.city.unique()

<StringArray>
[           'Chennai',              'Kochi',             'Mumbai',
          'Bangalore',              'Delhi', 'Thiruvananthapuram',
          'Hyderabad',          'Ahmedabad']
Length: 8, dtype: str

In [32]:
df.city.nunique()

8

In [33]:
df['city'].value_counts()

city
Kochi                 3
Chennai               2
Mumbai                2
Bangalore             2
Delhi                 2
Thiruvananthapuram    2
Hyderabad             1
Ahmedabad             1
Name: count, dtype: int64